# Generated by Django 4.2.6 on 2023-12-25 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ShopApp", "0003_tag_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="unique_id",
        ),
    ]
