# Generated by Django 4.2.6 on 2023-12-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ShopApp", "0004_remove_product_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unique_id",
            field=models.CharField(default="ee", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
