# Generated by Django 4.2.6 on 2023-12-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ShopApp", "0005_product_unique_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact_u",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("messgae", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
