# Generated by Django 4.2.6 on 2023-12-26 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ShopApp", "0006_contact_u"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact_u",
            new_name="Contact_us",
        ),
    ]
