# Generated by Django 4.2.6 on 2023-12-31 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ShopApp", "0008_rename_messgae_contact_us_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=250)),
                ("lastname", models.CharField(max_length=250)),
                ("country", models.CharField(max_length=250)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=250)),
                ("postcode", models.IntegerField()),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=250)),
                ("additional_info", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producr", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to="Product_image/Order")),
                ("quantity", models.CharField(max_length=250)),
                ("price", models.CharField(max_length=100)),
                ("total", models.CharField(max_length=250)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ShopApp.order"
                    ),
                ),
            ],
        ),
    ]
