# Generated by Django 4.2.6 on 2023-12-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ShopApp", "0009_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
