# Generated by Django 4.2.6 on 2023-12-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ShopApp", "0010_order_paid_order_payment_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="producr",
            new_name="product",
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
