# Generated by Django 4.2.6 on 2023-12-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ShopApp", "0011_rename_producr_orderitem_product_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
