# Generated by Django 4.2.6 on 2024-01-01 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ShopApp", "0012_alter_order_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="additional_info",
        ),
    ]
